### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by 12345-daredevil** [ZieMcd/HashiCorpVaultAsConfiguration#1]
Hello man. I can't run up your program. I use your guide on your site but I receive error. Can you help me?

**Comment by ZieMcd** [comment]
Hey @12345-daredevil, sure. The guide on the website is pretty bad and outdated sorry about that. 

Where are you getting the error, is it in code or while trying to set up vault locally?

**Comment by 12345-daredevil** [comment]
I have this problem in your project on my local machine Visual Studio (System.AggregateException: "One or more errors occurred. ({"errors":["permission denied"]})"). Unfortunately, I dont have enought knowlage to understand it. I follow on your guid. I try to find error but I dont know hashi vault.

**Comment by 12345-daredevil** [comment]
I change from token to root token and I get other error - "One or more errors occurred. ({"errors":["no handler for route \"kv-v2/data/secret/data/demo\". route entry not found."]}. I put (Path = "secret/data/demo"). May be I didnt right run up vault? I cant find secret path. This path I get from cmd and command C:\Users\Denis\Desktop\key>vault kv get secret/demo

**Comment by ZieMcd** [comment]
Ok, you might have configured it incorrectly. 

let's say you added your secret to vault with `vault kv put secret/demo secret-from-vault=hello`
your code should look like so 
```
builder.Configuration.AddVaultConfiguration(new VaultConfigSettings
{
    //Set up your vault settings here
    Token = "whatever your token is",
    ServerUriWithPort = "whatever uri your using, probably http://127.0.0.1:8200",
    MountPoint = "secret",
    Path = "demo"
});
```
also handy tip you can use `vault server -dev ui=true ` when starting vault and you will be able to use the vault ui at http://127.0.0.1:8200/ui

**Comment by 12345-daredevil** [comment]
Thanks! It works! I thoght about it very long time. But I have 1 question - I try to injection your solution in my project asp net core mvc. I dont know how I can get secrets without WebAPI. I want get string in my program.cs to have access to my DB. How I can change this code?

**Comment by ZieMcd** [comment]
It should be possible, do have the project in a repo so I can take a look.

**Comment by 12345-daredevil** [comment]
https://github.com/12345-daredevil/MyProgram

**Comment by ZieMcd** [comment]
@12345-daredevil I think if you add your connection string like so it should work
`vault kv put secret/demo ConnectionStrings:DefaultConnection= your connection string`

**Comment by 12345-daredevil** [comment]
I think too. But I dont know way how I can get this string in program.cs

`var connectionString = builder.Configuration.GetConnectionString("DefaultConnection");
            builder.Services.AddDbContext<ApplicationDbContext>(options =>
                options.UseSqlServer(connectionString));
`

I think I must put value in connectionString from Vault

**Comment by ZieMcd** [comment]
The code above should work if you start the project after adding the secret with that command.

**Comment by 12345-daredevil** [comment]
Thanks. I will try. But I dont understand how I can call method GetKey =)

**Comment by 12345-daredevil** [comment]
Thanks!!!!!!!! It works!

**Comment by ZieMcd** [comment]
Great! if you don't mind, I am going to close the issue.

**Comment by 12345-daredevil** [comment]
Good luck!

**Comment by 12345-daredevil** [comment]
I have some questions. Can I get your telegram if this possible?

**Comment by ZieMcd** [comment]
I don't have a telegram but feel free to email me at ziemcd@gmail.com
